---
- name: Install Web Sever Nginx
  apt:
          name=nginx
          update_cache=yes
          state=latest

- name: Create Virttual Host
  template:
          src: templates/default.conf
          dest: /etc/nginx/sites-enabled/{{ virtual_domain }}.conf

- name: Create home dir
  file:
          path: /var/www/{{ virtual_domain }}
          state: directory
          owner: '{{ nginx_user }}'
          group: '{{ nginx_user }}'
          mode: '0755'

- name: Restart Nginx
  systemd:
          name: nginx
          state: restarted