---
- name: Download Wordpress
  unarchive:
          src: https://wordpress.org/latest.tar.gz
          dest: /var/www/{{ virtual_domain }}
          remote_src: yes
          owner: '{{ nginx_user }}'
          group: '{{ nginx_user }}'